# Generated by Django 3.0.8 on 2020-10-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcourse',
            name='purchased',
        ),
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
